# Numpy

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

In [1]:
import numpy as np

In [2]:
b = np.array([1,2,3]) 

In [3]:
b

array([1, 2, 3])

In [4]:
b.shape

(3,)

# more than one dimensions 

In [5]:

a = np.array([[1, 2], [3, 4],[6,8]]) 

In [6]:
a

array([[1, 2],
       [3, 4],
       [6, 8]])

In [7]:
a.shape

(3, 2)

# dtype parameter 

In [8]:
 
a = np.array([1, 2, 3], dtype = complex) 

In [9]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
a = np.array([1, 2, 3], dtype = float) 

In [11]:
a

array([1., 2., 3.])

# shape, Size, Resize, np.arrange

In [12]:
a = np.array([[1,2,3,9],[4,5,6,0]]) 

In [13]:
a

array([[1, 2, 3, 9],
       [4, 5, 6, 0]])

In [14]:
a.shape

(2, 4)

In [15]:
a.size

8

In [16]:
a = np.array([[1,2,3],[4,5,6]]) 
#print(a.shape)
#a.shape = (3,2) 
a=np.reshape(a,(1,6))

In [17]:
a

array([[1, 2, 3, 4, 5, 6]])

In [18]:
a.shape=(2,3)

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b=a.reshape(3,2)

In [21]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
import numpy as np 
a = np.arange(24.0)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [24]:
import numpy as np 
a = np.arange(5,24)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23])

In [25]:
import numpy as np 
a = np.arange(5,24,1)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23])

In [26]:
import numpy as np 
a = np.arange(5,24,2)
a

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [27]:
import numpy as np 
a = np.arange(2,24,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [28]:
b=a.reshape(2,2,2)

In [29]:
b

array([[[ 2,  5],
        [ 8, 11]],

       [[14, 17],
        [20, 23]]])

In [30]:
b=a.reshape(2,2,2,1)

In [31]:
b

array([[[[ 2],
         [ 5]],

        [[ 8],
         [11]]],


       [[[14],
         [17]],

        [[20],
         [23]]]])

# numpy.empty

In [32]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
x

array([[16843008, 16843009],
       [16843009, 16843009],
       [16843009, 16843009]])

Note − The elements in an array show random values as they are not initialized.

In [33]:
import numpy as np 
x = np.empty([2,2], dtype = float) 
x

array([[3.2e-322, 4.9e-324],
       [0.0e+000, 0.0e+000]])

# numpy.zeros

In [34]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [35]:
x = np.zeros([5,5])

In [36]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
x = np.zeros([5,5,5,2])

In [38]:
x

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
       

# numpy.ones

In [39]:
x = np.ones([2,2], dtype = int) 
x

array([[1, 1],
       [1, 1]])

In [40]:
x = np.ones([2,2,2])

In [41]:
x

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [42]:
x = np.ones([1,2,2,2])

In [43]:
x

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [44]:
x = np.ones([2,1,2,2])

In [45]:
x

array([[[[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]]]])

# numpy.linspace

This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. 

In [47]:
import numpy as np 
x = np.linspace(1,50,retstep = True) 
print(x)


(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]), 1.0)


In [48]:
import numpy as np 
x = np.linspace(1,50,5,retstep = True) 
x

(array([ 1.  , 13.25, 25.5 , 37.75, 50.  ]), 12.25)

In [49]:
import numpy as np 
x = np.linspace(10,20,4) 
x

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [50]:
# endpoint set to false 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = False) 
x

array([10., 12., 14., 16., 18.])

In [51]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
x 
# retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [52]:
# find retstep value 
import numpy as np 

x = np.linspace(10,20,5, retstep = True) 
x 

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

# numpy.logspace

In [53]:
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0,num=10,base=2) 
a

array([2.        , 2.16011948, 2.33305808, 2.5198421 , 2.72158   ,
       2.93946898, 3.1748021 , 3.42897593, 3.70349885, 4.        ])

In [54]:
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

# NumPy - Indexing & Slicing

In [55]:
import numpy as np 
a = np.arange(10) 
print(a)
s = slice(2,7,3) 
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 5]


In [56]:
import numpy as np 
a = np.arange(10) 
print(a)
b = a[2:10:2] 
print (b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [57]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
b

5

In [58]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[4:])

[4 5 6 7 8 9]


In [59]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [60]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]' )
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [61]:
# this returns array of items in the second column 
print ('The items in the second column are:'  )
print (a[...,1])

The items in the second column are:
[2 4 5]


In [62]:
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...] )

The items in the second row are:
[3 4 5]


In [63]:
# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:' )
print (a[...,1:])

The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [64]:
# Now we will slice all items from column 2 onwards 
print ('The items column 2 onwards are:' )
print (a[...,2:])

The items column 2 onwards are:
[[3]
 [5]
 [6]]


In [65]:
# Now we will slice all items from column 1 onwards 
print ('The items column 2 onwards are:' )
print (a[...,0:])

The items column 2 onwards are:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [66]:
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[2,...] )

The items in the second row are:
[4 5 6]


# Find items on conditions

In [67]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

In [69]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [70]:
x[x >= 5]

array([ 5,  6,  7,  8,  9, 10, 11])

# NumPy - Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [71]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b
c

array([ 10,  40,  90, 160])

In [72]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:' )
print (a )
print ('\n')  
   
print ('Second array:' )
print (b )
print ('\n')  
   
print ('First Array + Second Array' )
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [73]:
print (a - b)

[[-1. -2. -3.]
 [ 9.  8.  7.]
 [19. 18. 17.]
 [29. 28. 27.]]


In [74]:
print (a * b)

[[ 0.  0.  0.]
 [10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]


In [75]:
print (a / b)

[[ 0.          0.          0.        ]
 [10.          5.          3.33333333]
 [20.         10.          6.66666667]
 [30.         15.         10.        ]]


In [76]:
print (b / a)

[[       inf        inf        inf]
 [0.1        0.2        0.3       ]
 [0.05       0.1        0.15      ]
 [0.03333333 0.06666667 0.1       ]]


c:\programdata\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


# NumPy - Arithmetic Operations

In [77]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print ('First array:' )
print (a )
print ('\n')  

print ('Second array:' )
b = np.array([10,10,10]) 
print (b) 
print ('\n'  )

print ('Add the two arrays:' )
print (np.add(a,b) )
print ('\n'  )

print ('Subtract the two arrays:' )
print (np.subtract(a,b) )
print ('\n')  

print ('Multiply the two arrays:' )
print (np.multiply(a,b) )
print ('\n')  

print ('Divide the two arrays:' )
print (np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [78]:
a=np.random.rand(3,2)

In [79]:
a

array([[0.61500006, 0.0063705 ],
       [0.82937882, 0.74862753],
       [0.01395208, 0.76506307]])

In [80]:
a=np.random.normal(3,2,10) #Mean, standard deviation

In [81]:
a

array([ 3.19811852,  5.66101038, -0.27165423,  0.06191428,  1.26374817,
        6.93412874,  3.17433058,  7.4042065 ,  2.93523145,  4.69231096])

In [82]:
a.mean()

3.5053345334852892

In [83]:
a.std()

2.543425703167336

In [84]:
a=np.random.uniform(2,4,10)

In [85]:
a

array([3.00191317, 3.68315232, 3.03418822, 2.4796958 , 2.32650793,
       2.63172436, 3.88177396, 3.87793844, 3.59543215, 3.90836131])